config/routes.rb
Rails.application.routes.draw do
  resources :receipeproducts
  resources :receipes
  resources :seasonproducts
  resources :seasons
  resources :compositionproducts
  resources :compositions
  resources :doshaproducts
  resources :doshas
  resources :categorizations
  resources :categories
  resources :products
  resources :products

  root 'products#index'

  post 'products/filter' => 'products#filter'

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
	 belongs_to :product
  	 belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :products, through: :categorizations
end

app/models/composition.rb
class Composition < ActiveRecord::Base
	has_many :compositionproducts
  	has_many :products, through: :compositionproducts	
end

app/models/compositionproduct.rb
class Compositionproduct < ActiveRecord::Base
	 belongs_to :product
  	 belongs_to :composition
end

app/models/dosha.rb
class Dosha < ActiveRecord::Base
	has_many :doshaproducts
  	has_many :products, through: :doshaproducts
end

app/models/doshaproduct.rb
class Doshaproduct < ActiveRecord::Base
	 belongs_to :product
  	 belongs_to :dosha	
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :categorizations
	has_many :categories, through: :categorizations

	has_many :doshaproducts
	has_many :doshas, through: :doshaproducts  	 

	has_many :compositionproducts
	has_many :compositions, through: :compositionproducts  	 
	
	has_many :seasonproducts
	has_many :seasons, through: :seasonproducts  	 

	has_many :receipeproducts
	has_many :receipes, through: :receipeproducts  
end

app/models/receipe.rb
class Receipe < ActiveRecord::Base
	has_many :seasonproducts
  	has_many :products, through: :seasonproducts	
end

app/models/receipeproduct.rb
class Receipeproduct < ActiveRecord::Base
	 belongs_to :product
  	 belongs_to :receipe	
end

app/models/season.rb
class Season < ActiveRecord::Base
	has_many :seasonproducts
  	has_many :products, through: :seasonproducts	
end

app/models/seasonproduct.rb
class Seasonproduct < ActiveRecord::Base
	 belongs_to :product
  	 belongs_to :season		
end

app/controllers/doshas_controller.rb
class DoshasController < ApplicationController
  before_action :set_dosha, only: [:show, :edit, :update, :destroy]

  # GET /doshas
  # GET /doshas.json
  def index
    @doshas = Dosha.all
  end

  # GET /doshas/1
  # GET /doshas/1.json
  def show
  end

  # GET /doshas/new
  def new
    @dosha = Dosha.new
  end

  # GET /doshas/1/edit
  def edit
  end

  # POST /doshas
  # POST /doshas.json
  def create
    @dosha = Dosha.new(dosha_params)

    respond_to do |format|
      if @dosha.save
        format.html { redirect_to @dosha, notice: 'Dosha was successfully created.' }
        format.json { render :show, status: :created, location: @dosha }
      else
        format.html { render :new }
        format.json { render json: @dosha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doshas/1
  # PATCH/PUT /doshas/1.json
  def update
    respond_to do |format|
      if @dosha.update(dosha_params)
        format.html { redirect_to @dosha, notice: 'Dosha was successfully updated.' }
        format.json { render :show, status: :ok, location: @dosha }
      else
        format.html { render :edit }
        format.json { render json: @dosha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doshas/1
  # DELETE /doshas/1.json
  def destroy
    @dosha.destroy
    respond_to do |format|
      format.html { redirect_to doshas_url, notice: 'Dosha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dosha
      @dosha = Dosha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dosha_params
      params.require(:dosha).permit(:name, :desc)
    end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:name, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/categorizations_helper.rb
module CategorizationsHelper
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/helpers/doshaproducts_helper.rb
module DoshaproductsHelper
end

app/helpers/doshas_helper.rb
module DoshasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipes_helper.rb
module ReceipesHelper
end

app/helpers/seasonproducts_helper.rb
module SeasonproductsHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/doshas/_form.html.erb
<%= form_for(@dosha) do |f| %>
  <% if @dosha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dosha.errors.count, "error") %> prohibited this dosha from being saved:</h2>

      <ul>
      <% @dosha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doshas/edit.html.erb
<h1>Editing Dosha</h1>

<%= render 'form' %>

<%= link_to 'Show', @dosha %> |
<%= link_to 'Back', doshas_path %>

app/views/doshas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doshas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doshas.each do |dosha| %>
      <tr>
        <td><%= dosha.name %></td>
        <td><%= dosha.desc %></td>
        <td><%= link_to 'Show', dosha %></td>
        <td><%= link_to 'Edit', edit_dosha_path(dosha) %></td>
        <td><%= link_to 'Destroy', dosha, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dosha', new_dosha_path %>

app/views/doshas/new.html.erb
<h1>New Dosha</h1>

<%= render 'form' %>

<%= link_to 'Back', doshas_path %>

app/views/doshas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dosha.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @dosha.desc %>
</p>

<%= link_to 'Edit', edit_dosha_path(@dosha) %> |
<%= link_to 'Back', doshas_path %>

app/views/seasons/_form.html.erb
<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing Season</h1>

<%= render 'form' %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Seasons</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seasons.each do |season| %>
      <tr>
        <td><%= season.name %></td>
        <td><%= season.desc %></td>
        <td><%= link_to 'Show', season %></td>
        <td><%= link_to 'Edit', edit_season_path(season) %></td>
        <td><%= link_to 'Destroy', season, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Season', new_season_path %>

app/views/seasons/new.html.erb
<h1>New Season</h1>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @season.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @season.desc %>
</p>

<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>