config/routes.rb
Rails.application.routes.draw do
  resources :receipeproducts
  resources :receipes
  resources :seasonproducts
  resources :seasons
  resources :compositionproducts
  resources :compositions
  resources :doshaproducts
  resources :doshas
  resources :categorizations
  resources :categories
  resources :products
  resources :products

  root 'products#index'

  post 'products/filter' => 'products#filter'

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
	 belongs_to :product
  	 belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :products, through: :categorizations
end

app/models/composition.rb
class Composition < ActiveRecord::Base
	has_many :compositionproducts
  	has_many :products, through: :compositionproducts	
end

app/models/compositionproduct.rb
class Compositionproduct < ActiveRecord::Base
	 belongs_to :product
  	 belongs_to :composition
end

app/models/dosha.rb
class Dosha < ActiveRecord::Base
	has_many :doshaproducts
  	has_many :products, through: :doshaproducts
end

app/models/doshaproduct.rb
class Doshaproduct < ActiveRecord::Base
	 belongs_to :product
  	 belongs_to :dosha	
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :categorizations
	has_many :categories, through: :categorizations

	has_many :doshaproducts
	has_many :doshas, through: :doshaproducts  	 

	has_many :compositionproducts
	has_many :compositions, through: :compositionproducts  	 
	
	has_many :seasonproducts
	has_many :seasons, through: :seasonproducts  	 

	has_many :receipeproducts
	has_many :receipes, through: :receipeproducts  
end

app/models/receipe.rb
class Receipe < ActiveRecord::Base
	has_many :seasonproducts
  	has_many :products, through: :seasonproducts	
end

app/models/receipeproduct.rb
class Receipeproduct < ActiveRecord::Base
	 belongs_to :product
  	 belongs_to :receipe	
end

app/models/season.rb
class Season < ActiveRecord::Base
	has_many :seasonproducts
  	has_many :products, through: :seasonproducts	
end

app/models/seasonproduct.rb
class Seasonproduct < ActiveRecord::Base
	 belongs_to :product
  	 belongs_to :season		
end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  before_action :set_composition, only: [:show, :edit, :update, :destroy]

  # GET /compositions
  # GET /compositions.json
  def index
    @compositions = Composition.all
  end

  # GET /compositions/1
  # GET /compositions/1.json
  def show
  end

  # GET /compositions/new
  def new
    @composition = Composition.new
  end

  # GET /compositions/1/edit
  def edit
  end

  # POST /compositions
  # POST /compositions.json
  def create
    @composition = Composition.new(composition_params)

    respond_to do |format|
      if @composition.save
        format.html { redirect_to @composition, notice: 'Composition was successfully created.' }
        format.json { render :show, status: :created, location: @composition }
      else
        format.html { render :new }
        format.json { render json: @composition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compositions/1
  # PATCH/PUT /compositions/1.json
  def update
    respond_to do |format|
      if @composition.update(composition_params)
        format.html { redirect_to @composition, notice: 'Composition was successfully updated.' }
        format.json { render :show, status: :ok, location: @composition }
      else
        format.html { render :edit }
        format.json { render json: @composition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compositions/1
  # DELETE /compositions/1.json
  def destroy
    @composition.destroy
    respond_to do |format|
      format.html { redirect_to compositions_url, notice: 'Composition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_composition
      @composition = Composition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def composition_params
      params.require(:composition).permit(:name, :desc, :unit)
    end
end

app/controllers/doshas_controller.rb
class DoshasController < ApplicationController
  before_action :set_dosha, only: [:show, :edit, :update, :destroy]

  # GET /doshas
  # GET /doshas.json
  def index
    @doshas = Dosha.all
  end

  # GET /doshas/1
  # GET /doshas/1.json
  def show
  end

  # GET /doshas/new
  def new
    @dosha = Dosha.new
  end

  # GET /doshas/1/edit
  def edit
  end

  # POST /doshas
  # POST /doshas.json
  def create
    @dosha = Dosha.new(dosha_params)

    respond_to do |format|
      if @dosha.save
        format.html { redirect_to @dosha, notice: 'Dosha was successfully created.' }
        format.json { render :show, status: :created, location: @dosha }
      else
        format.html { render :new }
        format.json { render json: @dosha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doshas/1
  # PATCH/PUT /doshas/1.json
  def update
    respond_to do |format|
      if @dosha.update(dosha_params)
        format.html { redirect_to @dosha, notice: 'Dosha was successfully updated.' }
        format.json { render :show, status: :ok, location: @dosha }
      else
        format.html { render :edit }
        format.json { render json: @dosha.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doshas/1
  # DELETE /doshas/1.json
  def destroy
    @dosha.destroy
    respond_to do |format|
      format.html { redirect_to doshas_url, notice: 'Dosha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dosha
      @dosha = Dosha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dosha_params
      params.require(:dosha).permit(:name, :desc)
    end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: [:show, :edit, :update, :destroy]

  # GET /seasons
  # GET /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1
  # GET /seasons/1.json
  def show
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
  end

  # POST /seasons
  # POST /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to @season, notice: 'Season was successfully created.' }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1
  # PATCH/PUT /seasons/1.json
  def update
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to @season, notice: 'Season was successfully updated.' }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1
  # DELETE /seasons/1.json
  def destroy
    @season.destroy
    respond_to do |format|
      format.html { redirect_to seasons_url, notice: 'Season was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def season_params
      params.require(:season).permit(:name, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/helpers/doshaproducts_helper.rb
module DoshaproductsHelper
end

app/helpers/doshas_helper.rb
module DoshasHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipes_helper.rb
module ReceipesHelper
end

app/helpers/seasonproducts_helper.rb
module SeasonproductsHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/compositions/1show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @composition.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @composition.desc %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @composition.unit %>
</p>

<%= link_to 'Edit', edit_composition_path(@composition) %> |
<%= link_to 'Back', compositions_path %>

app/views/compositions/_form.html.erb
<%= form_for(@composition) do |f| %>
  <% if @composition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@composition.errors.count, "error") %> prohibited this composition from being saved:</h2>

      <ul>
      <% @composition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compositions/edit.html.erb
<h1>Editing Composition</h1>

<%= render 'form' %>

<%= link_to 'Show', @composition %> |
<%= link_to 'Back', compositions_path %>

app/views/compositions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Compositions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compositions.each do |composition| %>
      <tr>
        <td><%= composition.name %></td>
        <td><%= composition.desc %></td>
        <td><%= composition.unit %></td>
        <td><%= link_to 'Show', composition %></td>
        <td><%= link_to 'Edit', edit_composition_path(composition) %></td>
        <td><%= link_to 'Destroy', composition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Composition', new_composition_path %>

app/views/compositions/new.html.erb
<h1>New Composition</h1>

<%= render 'form' %>

<%= link_to 'Back', compositions_path %>

app/views/compositions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @composition.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @composition.desc %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @composition.unit %>
</p>

<%= link_to 'Edit', edit_composition_path(@composition) %> |
<%= link_to 'Back', compositions_path %>

app/views/compositions/show.html.slim
.container
	.row
	  .col-sm-6.col-md-12
	      .caption
	        h3 = @composition.name
	        p = @composition.desc
	        p
	          = link_to 'Edit', edit_composition_path(@composition), class: 'btn btn-primary'
	          = link_to 'Back', compositions_path, class: 'btn btn-default'