config/routes.rb
Rails.application.routes.draw do
  resources :receipeproducts
  resources :receipes
  resources :seasonproducts
  resources :seasons
  resources :compositionproducts
  resources :compositions
  resources :doshaproducts
  resources :doshas
  resources :categorizations
  resources :categories
  resources :products
  resources :products

  root 'products#index'

  post 'products/filter' => 'products#filter'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :products, through: :categorizations
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
   include SmartListing::Helper::ControllerExtensions
    helper  SmartListing::Helper
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  skip_before_filter :verify_authenticity_token  

  # curl http://localhost:3000/categories.json
  # GET /categories
  # GET /categories.json
  def index
    categories_scope = Category.all
    categories_scope = categories_scope.where("name LIKE ?", "%#{params[:filter]}%") if params[:filter] 


    # @categories = Category.all
   smart_listing_create :categories, categories_scope, partial: "categories/list", page_sizes: [100]
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end
 
  # curl http://localhost:3000/categories.json -X POST -H 'Content-type: application/json' -d '{"name":"Специи","desc":"very"}'
  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    # binding.pry
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
 
  # curl http://localhost:3000/categories/21.json -X PUT -H 'Content-type: application/json' -d '{"name":"RtyСпеции"}'  
  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # curl http://localhost:3000/categories/21.json -X DELETE -H 'Content-type: application/json'   
  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc)
    end
end

 

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/1index.html.erb
<%= smart_listing_controls_for(:categories, {class: "form-inline text-right"}) do %>
  <div class="form-group filter input-append">
    <%= text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off %>
    
  </div>

  <button class="btn btn-primary disabled" type="<%= :submit %>">
    <span class="glyphicon glyphicon-search"></span>
  </button>

<% end %>
<%= smart_listing_render(:categories) %>

app/views/categories/_1form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_form.html.slim
= simple_form_for(@category, html: { class: 'form-horizontal' }) do |f|
	= f.input :name
	= f.input :desc
	= f.button :submit

app/views/categories/_list.html.erb
<% unless smart_listing.empty? %>
  <table class="table table-striped">
    
    <tbody>
      <% smart_listing.collection.each do |category| %>
        <tr>
           <td><%= link_to(category.name, category_path(category)) %></td>
           <td><%= category.desc %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
 <% else %>
  <p class="warning">No records!</p>
<% end %>

app/views/categories/edit.html.slim
.container
	.col-md-4.col-md-offset-4
		h3 Editing Category

		= render 'form' 

		= link_to 'Show', @category
		= link_to 'Back', categories_path

app/views/categories/index.html.erb
<%= smart_listing_controls_for(:categories, {class: "form-inline text-right"}) do %>
  <div class="form-group filter input-append">
    <%= text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off %>
    
  </div>

  <button class="btn btn-primary disabled" type="<%= :submit %>">
    <span class="glyphicon glyphicon-search"></span>
  </button>

<% end %>
<%= smart_listing_render(:categories) %>

app/views/categories/index.html.slim
.container
	= smart_listing_controls_for(:categories, {class: "form-inline text-right"}) do
	  .form-group.filter.input-append
	    = text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off
	  button.btn.btn-primary.disabled type=:submit 
	    span.glyphicon.glyphicon-search
	= smart_listing_render(:categories)

app/views/categories/index.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :categories %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @category.desc %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>