config/routes.rb
Rails.application.routes.draw do
  resources :receipeproducts
  resources :receipes
  resources :seasonproducts
  resources :seasons
  resources :compositionproducts
  resources :compositions
  resources :doshaproducts
  resources :doshas
  resources :categorizations
  resources :categories
  resources :products
  resources :products

  root 'products#index'

  post 'products/filter' => 'products#filter'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :categorizations
	has_many :categories, through: :categorizations

	has_many :doshaproducts
	has_many :doshas, through: :doshaproducts  	 

	has_many :compositionproducts
	has_many :compositions, through: :compositionproducts  	 
	
	has_many :seasonproducts
	has_many :seasons, through: :seasonproducts  	 

	has_many :receipeproducts
	has_many :receipes, through: :receipeproducts  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
    helper  SmartListing::Helper

  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @comps = Composition.all
    @product = Product.new

    products_scope = Product.all
    products_scope = products_scope.where("name LIKE ?", "%#{params[:filter]}%")  if params[:filter]
    @products = smart_listing_create :products, products_scope, partial: "products/list",  page_sizes: [500]
  end

  def filter
    composition_id = params[:product][:compositions]
    p "ID:#{composition_id}"

    # binding.pry

    @comp = Composition.find(composition_id) if composition_id

    @comps = Composition.all
    @product = Product.new

    products = @comp.products
    products_scope = products.order('compositionproducts.quantity desc')
    # products_scope = @comp.products
       
    @products = smart_listing_create :products, products_scope, partial: "products/list",  page_sizes: [100]
    render 'index'
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :desc, :img_url)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br>
    <%= f.text_field :img_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_list.html.slim
p#notice= notice

.panel.panel-default
  /! Default panel contents
  .panel-heading 
    = simple_form_for(@product, url:'products/filter') do |f|
      = f.input :compositions, collection: @comps, label: 'По составу', value_method: :id, :multiple => true
      / <%= f.input :location,:collection => @locations,:label_method => :location_name,:value_method => :id,:label => "Location" ,:include_blank => false
      = f.button :submit, 'Применить фильтр'
      .col-md-offset-10
        - if @comp
          h5 = link_to(@comp.name.capitalize,composition_path(@comp))

  .panel-body
  
  table.table-hover
    thead
      
    tbody
      -  smart_listing.collection.each do |product|  
        tr
          td 
            h4 = product.name

        tr
          td.col-md-2= link_to(image_tag(product.img_url, size: '150'),product)
          td.col-md-8= product.desc[0..400]
          - if @comp
            td.col-md-2= product.compositionproducts.find_by_composition_id(@comp.id).quantity.to_s+@comp.unit.to_s


          
          
  br/
  = link_to 'New Product', new_product_path

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.slim
.container
	
	h1.col-md-offset-5 Продукты	
	 
	
	= smart_listing_controls_for(:products, {class: "form-inline text-right"}) do
	  .form-group.filter.input-append
	    = text_field_tag :filter, '', class: "search form-control", placeholder: "Search...", autocomplete: :off
	  button.btn.btn-primary.disabled type=:submit 
	    span.glyphicon.glyphicon-search
	= smart_listing_render(:products)

app/views/products/index.js.erb
<%# Render list for XHR requests %>
<%= smart_listing_update :products %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.slim
.container
	.row
	  .col-sm-6.col-md-12
	    .thumbnail
	      = image_tag(@product.img_url, size:'300')
	      .caption
	        h3 = @product.name
	        p = @product.desc
	        p
	          = link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary'
	          = link_to 'Back', products_path, class: 'btn btn-default'

 

	